"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Search, Plus, ScanLine, MapPin, ImagePlus, X, Camera, ShieldCheck, LoaderCircle, Pencil, Trash2, Check, Crosshair, FolderOpen, Sparkles } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Toaster, toast } from "sonner";
import { samplePhoto, searchPhotos, type Photo, type Item } from "@/lib/findit";
import { preparePhoto, detectItems } from "@/lib/detection";
import { listPhotos, savePhoto, deletePhoto, releasePhotoUrls } from "@/lib/browser-storage";

type Draft=Photo & {blob?:Blob};

function ObjectBoxes({items,active,onSelect}:{items:Item[];active?:string|null;onSelect?:(id:string)=>void}){return <>{items.filter(i=>i.box&&(!active||i.id===active)).map(item=>{const b=item.box!;return <button key={item.id} type="button" className="object-box" style={{left:`${b[0]*100}%`,top:`${b[1]*100}%`,width:`${b[2]*100}%`,height:`${b[3]*100}%`}} aria-label={`Highlight ${item.label}`} onClick={e=>{e.stopPropagation();onSelect?.(item.id)}}><span style={b[1]<.08?{top:4,bottom:"auto"}:undefined}>{item.label}</span></button>})}</>}
export default function FindIt(){
 const [photos,setPhotos]=useState<Photo[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 const [query,setQuery]=useState(""),[location,setLocation]=useState("All locations"),[draft,setDraft]=useState<Draft|null>(null),[active,setActive]=useState<string|null>(null);
 const [label,setLabel]=useState(""),[drawing,setDrawing]=useState(false),[drag,setDrag]=useState<[number,number,number,number]|null>(null),[detecting,setDetecting]=useState(false),[detectionNote,setDetectionNote]=useState("");
 const [saving,setSaving]=useState(false),[error,setError]=useState(""),[deleting,setDeleting]=useState(false),[deleteConfirm,setDeleteConfirm]=useState(false);
 const inputRef=useRef<HTMLInputElement>(null),searchRef=useRef<HTMLInputElement>(null),token=useRef(0),start=useRef<[number,number]|null>(null),tempURL=useRef<string|null>(null);
 const [showSample,setShowSample]=useState(false);
 async function load(){setLoading(true);setLoadError("");try{setPhotos(await listPhotos());}catch(e){setLoadError(e instanceof Error?e.message:"Could not open this browser’s photo library.");}finally{setLoading(false)}}
 useEffect(()=>{void load();return()=>{if(tempURL.current)URL.revokeObjectURL(tempURL.current);releasePhotoUrls();}},[]);
 const library=useMemo(()=>photos.length===0||showSample?[...photos,samplePhoto]:photos,[photos,showSample]);
 const results=useMemo(()=>searchPhotos(library,query,location),[library,query,location]);
 const locations=Array.from(new Set(library.map(p=>p.location)));
 const totalItems=photos.reduce((n,p)=>n+p.items.length,0);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:"search_belongings",title:"Search FindIt",description:"Search saved photo labels and locations and show matching belongings. Does not modify saved records.",inputSchema:{type:"object",properties:{query:{type:"string",maxLength:200}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input:unknown){if(!input||typeof input!=="object"||!("query" in input)||typeof input.query!=="string"||input.query.length>200)throw new Error("Provide a search query of up to 200 characters.");setQuery(input.query);setLocation("All locations");await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return searchPhotos(library,input.query).map(r=>({location:r.photo.location,sample:!!r.photo.sample,items:r.matches.map(i=>i.label)}));}}, {signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[library]);
 function close(){if(saving||deleting)return;token.current++;setDraft(null);setDrawing(false);setDrag(null);setDetecting(false);setError("");if(tempURL.current){URL.revokeObjectURL(tempURL.current);tempURL.current=null;}}
 function openPhoto(p:Photo){token.current++;setDraft({...p,items:p.items.map(i=>({...i}))});setActive(query?searchPhotos([p],query)[0]?.matches[0]?.id||null:null);setLabel("");setDrawing(false);setError("");setDetectionNote("");setDetecting(false);}
 async function detect(d:Draft){const current=++token.current;setDetecting(true);setDetectionNote("");try{const img=new Image();img.src=d.imageUrl;await img.decode();let timeout:ReturnType<typeof setTimeout>|undefined;const items=await Promise.race([detectItems(img),new Promise<never>((_,reject)=>{timeout=setTimeout(()=>reject(new Error("Detection took too long. You can add labels manually or retry.")),60000)})]).finally(()=>clearTimeout(timeout));if(token.current!==current)return;setDraft(p=>p?{...p,items:[...p.items.filter(i=>i.source==="manual"),...items]}:p);setDetectionNote(items.length?`${items.length} objects suggested. Review their names and remove any mistakes.`:"No common objects were recognized. Add your own labels below.");}catch(e){if(token.current===current)setDetectionNote(e instanceof Error?e.message:"Automatic detection is unavailable. You can still label your items.");}finally{if(token.current===current)setDetecting(false)}}
 async function upload(file:File){setError("");try{const prepared=await preparePhoto(file);if(tempURL.current)URL.revokeObjectURL(tempURL.current);tempURL.current=prepared.url;const d:Draft={id:"new",location:"",notes:"",items:[],createdAt:"",width:prepared.width,height:prepared.height,imageUrl:prepared.url,blob:prepared.blob};setDraft(d);setActive(null);setLabel("");setDrawing(false);void detect(d);}catch(e){toast.error(e instanceof Error?e.message:"Could not open this photo.")}}
 function addItem(box:Item["box"]){if(!label.trim()||!draft||draft.items.length>=60||detecting)return;const id=crypto.randomUUID();setDraft({...draft,items:[...draft.items,{id,label:label.trim().slice(0,100),box,source:"manual"}]});setActive(id);setLabel("");setDrawing(false);setDrag(null);}
 function point(e:React.PointerEvent<HTMLDivElement>):[number,number]{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]}
 function pointerDown(e:React.PointerEvent<HTMLDivElement>){if(!drawing)return;e.preventDefault();start.current=point(e);e.currentTarget.setPointerCapture(e.pointerId);setDrag([start.current[0],start.current[1],0,0]);}
 function pointerMove(e:React.PointerEvent<HTMLDivElement>){if(!drawing||!start.current)return;const p=point(e),s=start.current;setDrag([Math.min(p[0],s[0]),Math.min(p[1],s[1]),Math.abs(p[0]-s[0]),Math.abs(p[1]-s[1])]);}
 function pointerUp(e:React.PointerEvent<HTMLDivElement>){if(!drawing||!start.current)return;const p=point(e),s=start.current;let box:[number,number,number,number]=[Math.min(p[0],s[0]),Math.min(p[1],s[1]),Math.abs(p[0]-s[0]),Math.abs(p[1]-s[1])];if(box[2]<.015||box[3]<.015)box=[Math.max(0,Math.min(.88,p[0]-.06)),Math.max(0,Math.min(.88,p[1]-.06)),.12,.12];start.current=null;addItem(box);}
 async function save(){if(!draft||draft.sample)return;if(!draft.location.trim()){setError("Give this photo a location so you can find your items later.");return;}setSaving(true);setError("");try{const photo=await savePhoto(draft);setPhotos(p=>[photo,...p.filter(x=>x.id!==photo.id)]);setQuery("");setLocation("All locations");setDraft(null);token.current++;if(tempURL.current){URL.revokeObjectURL(tempURL.current);tempURL.current=null;}toast.success(draft.blob?"Photo saved in this browser. Your items are now searchable.":"Photo updated.");}catch(e){setError(e instanceof Error?e.message:"Could not save your photo.");}finally{setSaving(false)}}
 async function remove(){if(!draft||draft.sample)return;setDeleting(true);setError("");try{await deletePhoto(draft.id);setPhotos(p=>p.filter(x=>x.id!==draft.id));setDraft(null);setLocation("All locations");toast.success("Photo deleted.");}catch(e){setError(e instanceof Error?e.message:"Could not delete this photo.");}finally{setDeleting(false);setDeleteConfirm(false)}}
 return <div className="app-shell">
  <Toaster position="bottom-center" richColors />
  <input ref={inputRef} type="file" className="sr-only" accept="image/jpeg,image/png,image/webp" aria-label="Upload a photo" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value="";}}/>
  <header className="site-header"><a className="brand" href={import.meta.env.BASE_URL} aria-label="FindIt home"><span className="brand-icon"><Search size={24}/><i/></span>findit<span className="brand-period">.</span></a><div className="header-caption">A little less searching.<br/><strong>A little more living.</strong></div><div className="header-actions"><button className="text-button" onClick={()=>{setShowSample(true);setQuery("");setLocation("All locations");openPhoto(samplePhoto)}}>Try a sample</button><button className="primary-button" onClick={()=>inputRef.current?.click()}><Plus size={18}/>Add photo</button></div></header>
  <main>
   <section className="search-section"><div className="eyebrow"><ScanLine size={16}/>YOUR VISUAL MEMORY</div><h1>Where did you put it?</h1><p>Search your things. Find their place.</p><div className="search-field"><Search size={23}/><input ref={searchRef} aria-label="Search your belongings" placeholder="Try ‘Where is my remote?’" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" aria-label="Clear search" onClick={()=>{setQuery("");searchRef.current?.focus()}}><X size={18}/></button>}<span className="search-key"><ScanLine size={18}/></span></div><div className="search-suggestions"><span>Try searching</span>{["Remote","Scissors","Charger"].map(t=><button key={t} onClick={()=>{setQuery(t);setLocation("All locations")}}>{t}<Search size={12}/></button>)}</div></section>
   <section className="library-section"><div className="section-heading"><div><h2>{query?`Results for “${query}”`:"Your photo library"}</h2><p>{query?`${results.length} matching ${results.length===1?"photo":"photos"}`:photos.length?`${photos.length} ${photos.length===1?"photo":"photos"} · ${totalItems} labeled items`:"A home for everything you want to find again."}</p></div><Select value={location} onValueChange={setLocation}><SelectTrigger className="location-select" aria-label="Filter by location"><MapPin size={16}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="All locations">All locations</SelectItem>{locations.map(l=><SelectItem key={l} value={l}>{l}</SelectItem>)}</SelectContent></Select></div>
   {loadError&&<div className="error-banner" role="alert">{loadError}<button onClick={()=>void load()}>Retry</button></div>}
   {loading?<div className="photo-grid"><Skeleton className="h-80 rounded-2xl"/><Skeleton className="h-80 rounded-2xl"/></div>:<div className={`photo-grid ${!photos.length&&!query?"first-photo-grid":""}`}>
    {results.map(({photo,matches:found})=><article className="photo-card" key={photo.id}><div className="card-image" role="button" tabIndex={0} aria-label={`Open ${photo.location}`} onClick={()=>openPhoto(photo)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openPhoto(photo)}}}><img src={photo.imageUrl} alt={`Items photographed at ${photo.location}`} loading="lazy"/>{photo.sample&&<span className="sample-badge">SAMPLE PHOTO</span>}<ObjectBoxes items={query?found:photo.sample?[photo.items[4]]:[]} onSelect={id=>{openPhoto(photo);setActive(id)}}/><span className="photo-open"><ScanLine size={18}/>Explore photo</span></div><div className="card-body"><div><h3><MapPin size={17}/>{photo.location}</h3><p>{photo.items.length} labeled items <span>·</span> {photo.sample?"Try it out":new Date(photo.createdAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</p></div><button className="icon-button" aria-label={`View ${photo.location}`} onClick={()=>openPhoto(photo)}><ScanLine size={21}/></button></div>{query&&found.length>0&&<div className="match-tags">{found.map(i=><button key={i.id} onClick={()=>{openPhoto(photo);setActive(i.id)}}><Check size={14}/>{i.label}</button>)}</div>}</article>)}
    {!query&&<button className="upload-card" onClick={()=>inputRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)void upload(f)}}><span className="upload-icon"><ImagePlus size={29}/></span><h3>{photos.length?"Remember another space":"Give your things a place"}</h3><p>Snap a shelf, a drawer, or a packed box.<br/>We’ll help you remember what’s inside.</p><span className="upload-call"><Plus size={17}/>{photos.length?"Add another photo":"Add your first photo"}</span><small>Drop an image here · JPG, PNG, WebP</small></button>}
    {query&&results.length===0&&<div className="no-results"><Search size={34}/><h3>No matches yet</h3><p>Try a simpler name or another location. Items need a saved label to appear in search.</p><button className="secondary-button" onClick={()=>{setQuery("");setLocation("All locations")}}>Show all photos</button></div>}
   </div>}
   {!photos.length&&!query&&<div className="sample-note"><Sparkles size={15}/>The sample is an AI-generated desk with hand-labeled items. Upload your own photo to try automatic detection.</div>}
   </section>
   <section className="how-row" aria-label="How FindIt works"><div><span>01</span><div><h3>Capture a space</h3><p>A clear photo is all you need.</p></div></div><div><span>02</span><div><h3>Give it a location</h3><p>Review labels and add your own.</p></div></div><div><span>03</span><div><h3>Find it in a moment</h3><p>Search a name. See its last saved place.</p></div></div></section>
  </main><footer><span><ShieldCheck size={15}/>Saved only in this browser. Clearing site data removes your library.</span><span>FindIt remembers photos, not live locations.</span></footer>
  <Dialog open={!!draft} onOpenChange={v=>{if(!v)close()}}><DialogContent className="photo-dialog" onInteractOutside={e=>{if(saving||detecting)e.preventDefault()}}><DialogHeader><DialogTitle>{draft?.sample?"Explore the sample":draft?.blob?"Remember this space":"Your saved space"}</DialogTitle><DialogDescription>{draft?.sample?"Select a labeled item to see where it appears.":"Save a location, review the suggested items, and label anything we missed."}</DialogDescription></DialogHeader>{draft&&<><div className="editor-grid"><div className="editor-photo-column"><div className={`editor-image ${drawing?"drawing":""}`} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={()=>{start.current=null;setDrag(null)}}><img src={draft.imageUrl} alt={`Photo of ${draft.location||"your space"}`} draggable={false}/>{!drawing&&<ObjectBoxes items={draft.items} active={active} onSelect={setActive}/>} {drag&&<span className="draw-box" style={{left:`${drag[0]*100}%`,top:`${drag[1]*100}%`,width:`${drag[2]*100}%`,height:`${drag[3]*100}%`}}/>}</div><div className="image-caption"><Crosshair size={15}/>{drawing?`Draw around “${label}”, or tap to place a marker.`:active?"Highlighted in the photo. Select another item to locate it.":"Select an item to highlight its position."}</div>{draft.sample&&<p className="muted small">Sample labels were added manually. Automatic detection may recognize fewer objects.</p>}</div>
   <div className="editor-controls">{draft.sample?<div className="sample-location"><MapPin size={20}/><div><h3>{draft.location}</h3><p>6 hand-labeled items</p></div></div>:<><label className="field-label" htmlFor="location">Where is this?</label><input id="location" className="text-input" placeholder="e.g. Bedroom · Top drawer" value={draft.location} maxLength={100} onChange={e=>setDraft({...draft,location:e.target.value})}/><label className="field-label" htmlFor="notes">Extra details <span>optional</span></label><input id="notes" className="text-input" placeholder="e.g. Left side, behind the books" value={draft.notes} maxLength={500} onChange={e=>setDraft({...draft,notes:e.target.value})}/></>}
   <div className="items-heading"><h3>Items in this photo <span>{draft.items.length}</span></h3>{active&&<button className="text-button" onClick={()=>setActive(null)}>Show all</button>}</div>
   {detecting&&<div className="detect-status" role="status"><LoaderCircle size={18} className="spin"/><div>Looking for common objects…<small>The first scan downloads the detection model.</small></div></div>}
   {!detecting&&detectionNote&&<p className="detection-note" role="status">{detectionNote}</p>}
   <div className="items-list">{draft.items.map(item=><div key={item.id} className={`item-row ${active===item.id?"active":""}`}><button className="item-locator" aria-label={`Locate ${item.label}`} onClick={()=>setActive(item.id)}><Crosshair size={17}/></button>{draft.sample?<button className="item-name" onClick={()=>setActive(item.id)}>{item.label}</button>:<input aria-label={`Item name: ${item.label}`} value={item.label} maxLength={100} onChange={e=>setDraft({...draft,items:draft.items.map(i=>i.id===item.id?{...i,label:e.target.value}:i)})}/>}<span className="item-source">{item.source==="detected"?`${Math.round((item.confidence||0)*100)}%`:item.source==="sample"?"Sample":"Yours"}</span>{!draft.sample&&<button className="icon-button" aria-label={`Remove ${item.label}`} onClick={()=>setDraft({...draft,items:draft.items.filter(i=>i.id!==item.id)})}><X size={15}/></button>}</div>)}</div>
   {!draft.sample&&<><div className="add-label"><label className="field-label" htmlFor="new-label">Add an item we missed</label><input id="new-label" className="text-input" placeholder="e.g. USB-C charger" value={label} maxLength={100} onChange={e=>setLabel(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addItem(null)}}}/><div className="label-actions"><button className="secondary-button" disabled={!label.trim()||detecting||draft.items.length>=60} onClick={()=>setDrawing(!drawing)}><Pencil size={14}/>{drawing?"Cancel marking":"Mark on photo"}</button><button className="text-button" disabled={!label.trim()||detecting||draft.items.length>=60} onClick={()=>addItem(null)}>Add label only</button></div></div><button className="rescan text-button" disabled={detecting||saving} onClick={()=>void detect(draft)}><ScanLine size={16}/>{detectionNote?"Retry detection":"Scan for objects"}</button><p className="muted small">Detection recognizes common categories, not every object. Review labels before saving. Search uses names and common synonyms.</p></>}
   </div></div>{error&&<div className="error-banner" role="alert">{error}</div>}<div className="dialog-bottom"><div>{!draft.sample&&!draft.blob&&<button className="text-button delete-button" onClick={()=>setDeleteConfirm(true)} disabled={saving||deleting}><Trash2 size={16}/>Delete photo</button>}</div><div>{draft.sample?<><button className="secondary-button" onClick={()=>{close();setTimeout(()=>inputRef.current?.click(),0)}}><Camera size={17}/>Try your own photo</button><button className="primary-button" onClick={close}>Done</button></>:<><button className="secondary-button" onClick={close} disabled={saving}>Cancel</button><button className="primary-button" onClick={()=>void save()} disabled={saving||detecting||draft.items.some(i=>!i.label.trim())}>{saving?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>} {saving?"Saving…":draft.blob?"Save photo":"Save changes"}</button></>}</div></div></>}</DialogContent></Dialog>
  <AlertDialog open={deleteConfirm} onOpenChange={setDeleteConfirm}><AlertDialogContent><AlertDialogTitle>Delete this photo?</AlertDialogTitle><AlertDialogDescription>The photo and its labels will be removed from your library. This cannot be undone.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep photo</AlertDialogCancel><AlertDialogAction onClick={()=>void remove()} className="bg-red-700">Delete photo</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
