import { env } from "cloudflare:workers";
import { z } from "zod";
export function storage(){ if(!env.DB||!env.BUCKET) throw new Error("Photo storage is unavailable.");return {db:env.DB,bucket:env.BUCKET}; }
export function identity(request: Request){const user=request.headers.get("oai-authenticated-user-id");if(!user) throw new ApiError(401,"Sign in to save and view your photos.");return user;}
export function checkOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new ApiError(403,"This request could not be verified.");}
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export function apiError(error:unknown){if(error instanceof ApiError)return Response.json({error:error.message},{status:error.status});if(error instanceof z.ZodError)return Response.json({error:"Check the location and item labels, then try again."},{status:400});console.error("FindIt storage error",error);return Response.json({error:"We couldn’t reach your photo storage. Please try again; your changes are still here."},{status:503});}
export const itemSchema=z.object({id:z.string().min(1).max(100),label:z.string().trim().min(1).max(100),source:z.enum(["detected","manual"]),confidence:z.number().min(0).max(1).optional(),box:z.tuple([z.number().min(0).max(1),z.number().min(0).max(1),z.number().positive().max(1),z.number().positive().max(1)]).nullable()}).refine(v=>!v.box||(v.box[0]+v.box[2]<=1.02&&v.box[1]+v.box[3]<=1.02),"Invalid item bounds");
export const metadataSchema=z.object({location:z.string().trim().min(1).max(100),notes:z.string().trim().max(500).default(""),items:z.array(itemSchema).max(60),width:z.number().int().min(1).max(4000),height:z.number().int().min(1).max(4000)});
export type Row={id:string;location:string;notes:string;items:string;width:number;height:number;created_at:string;object_key:string;content_type:string};
export function photoDTO(row:Row){return {id:row.id,location:row.location,notes:row.notes,items:JSON.parse(row.items),width:row.width,height:row.height,createdAt:row.created_at,imageUrl:`/api/photos/${row.id}/image`};}
export async function ownedPhoto(id:string,owner:string){if(!/^[a-f0-9-]{36}$/.test(id))throw new ApiError(404,"Photo not found.");const {db}=storage();const row=await db.prepare("SELECT * FROM photos WHERE id = ? AND owner = ?").bind(id,owner).first<Row>();if(!row)throw new ApiError(404,"Photo not found.");return row;}
export async function boundedBody(request:Request,limit:number){const reader=request.body?.getReader();if(!reader)throw new ApiError(400,"Missing photo data.");const chunks:Uint8Array[]=[];let total=0;while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw new ApiError(413,"This photo is too large.");}chunks.push(value);}return new Blob(chunks as BlobPart[]);}
